# https://github.com/willhallonline/docker-ansible/blob/v4.2.0/ansible-base/alpine314/Dockerfile
# pull base image
FROM alpine:3.14

#2.10.16> #2.10.17
ENV ANSIBLE_VERSION "2.10.17"
# ANSIBLE_LINT_210: 5.4.0 ##https://github.com/willhallonline/docker-ansible/blob/master/.gitlab-ci.yml
ENV ANSIBLE_LINT_VERSION "5.4.0"

# # Labels.
# LABEL maintainer="will@willhallonline.co.uk" \
#     org.label-schema.schema-version="1.0" \
#     org.label-schema.build-date=$BUILD_DATE \
#     org.label-schema.vcs-ref=$VCS_REF \
#     org.label-schema.name="willhallonline/ansible" \
#     org.label-schema.description="Ansible inside Docker" \
#     org.label-schema.url="https://github.com/willhallonline/docker-ansible" \
#     org.label-schema.vcs-url="https://github.com/willhallonline/docker-ansible" \
#     org.label-schema.vendor="Will Hall Online" \
#     org.label-schema.docker.cmd="docker run --rm -it -v $(pwd):/ansible ~/.ssh/id_rsa:/root/id_rsa willhallonline/ansible:2.10-alpine-3.14"

# RUN export domain="mirrors.aliyun.com"; \
RUN export domain="mirrors.ustc.edu.cn"; \
  echo "http://$domain/alpine/v3.14/main" > /etc/apk/repositories; \
  echo "http://$domain/alpine/v3.14/community" >> /etc/apk/repositories


RUN apk --no-cache add \
        sudo \
        python3\
        py3-pip \
        openssl \
        ca-certificates \
        sshpass \
        openssh-client \
        rsync \
        git && \
    apk --no-cache add --virtual build-dependencies \
        python3-dev \
        libffi-dev \
        musl-dev \
        gcc \
        cargo \
        openssl-dev \
        libressl-dev \
        build-base && \
    pip3 install --upgrade pip wheel && \
    pip3 install --upgrade cryptography cffi && \
    pip3 install ansible-base==${ANSIBLE_VERSION} && \
    pip3 install mitogen ansible-lint==${ANSIBLE_LINT_VERSION} jmespath && \
    pip3 install --upgrade pywinrm && \
    # rdeck's ansible-hosts
    pip3 install jinja2==2.10.1 && \
    pip3 install markupsafe==1.1.1 && \
    # 
    apk del build-dependencies && \
    rm -rf /var/cache/apk/* && \
    rm -rf /root/.cache/pip && \
    rm -rf /root/.cargo

RUN mkdir /ansible && \
    mkdir -p /etc/ansible && \
    echo 'localhost' > /etc/ansible/hosts

WORKDIR /ansible

CMD [ "ansible-playbook", "--version" ]