# https://github.com/willhallonline/docker-ansible/blob/v2.5.0/ansible29/alpine310/Dockerfile
# pull base image
FROM alpine:3.10

# Labels.
# LABEL maintainer="will@willhallonline.co.uk" \
#     org.label-schema.schema-version="1.0" \
#     org.label-schema.build-date=$BUILD_DATE \
#     org.label-schema.vcs-ref=$VCS_REF \
#     org.label-schema.name="willhallonline/ansible" \
#     org.label-schema.description="Ansible inside Docker" \
#     org.label-schema.url="https://github.com/willhallonline/docker-ansible" \
#     org.label-schema.vcs-url="https://github.com/willhallonline/docker-ansible" \
#     org.label-schema.vendor="Will Hall Online" \
#     org.label-schema.docker.cmd="docker run --rm -it -v $(pwd):/ansible -v ~/.ssh/id_rsa:/root/id_rsa willhallonline/ansible:2.8-alpine-3.10"

# RUN export domain="mirrors.aliyun.com"; \
RUN export domain="mirrors.ustc.edu.cn"; \
  echo "http://$domain/alpine/v3.10/main" > /etc/apk/repositories; \
  echo "http://$domain/alpine/v3.10/community" >> /etc/apk/repositories


RUN apk --no-cache add \
        sudo \
        python3\
        py3-pip \
        openssl \
        ca-certificates \
        sshpass \
        openssh-client \
        rsync \
        git && \
    apk --no-cache add --virtual build-dependencies \
        python3-dev \
        libffi-dev \
        openssl-dev \
        build-base && \
    pip3 install --upgrade pip cffi && \
    # # ERROR! Your version of Ansible ((2, 8, 8)) is too old. The oldest version supported by Mitogen for Ansible is (2, 10).
    # https://github.com/willhallonline/docker-ansible/blob/v2.5.0/ansible210/alpine310/Dockerfile
    # hand try>> dcp-rundeck:/srv/local/rundeck# pip3 install ansible==2.10.7
    pip3 install ansible==2.10.7 && \
    pip3 install mitogen ansible-lint jmespath && \
    pip3 install --upgrade pywinrm && \
    # rdeck's ansible-hosts
    pip3 install jinja2==2.10.1 && \
    pip3 install markupsafe==1.1.1 && \
    apk del build-dependencies && \
    rm -rf /var/cache/apk/*

RUN mkdir /ansible && \
    mkdir -p /etc/ansible && \
    echo 'localhost' > /etc/ansible/hosts

WORKDIR /ansible

CMD [ "ansible-playbook", "--version" ]