# https://github.com/willhallonline/docker-ansible/blob/v4.3.2/.gitlab-ci.yml
    #   ANSIBLE_CORE_29: 2.9.27
    #   ANSIBLE_CORE_210: 2.10.17
    #   ANSIBLE_CORE_211: 2.11.12
    #   ANSIBLE_CORE_212: 2.12.9
    #   ANSIBLE_CORE_213: 2.13.7
    #   ANSIBLE_LINT_213: 5.4.0
    #   ANSIBLE_213: 6.7.0
    # docker build --pull -t "$CI_REGISTRY_IMAGE:2.13-alpine-3.14" -t "$DOCKER_HUB_REGISTRY_IMAGE:2.13-alpine-3.14" -t "$CI_REGISTRY_IMAGE:$ANSIBLE_CORE_213-alpine-3.14" -t "$DOCKER_HUB_REGISTRY_IMAGE:$ANSIBLE_CORE_213-alpine-3.14" \
    # --build-arg ANSIBLE_CORE_VERSION=${ANSIBLE_CORE_213} \
    # --build-arg ANSIBLE_VERSION=${ANSIBLE_213} \
    # --build-arg ANSIBLE_LINT=${ANSIBLE_LINT_213} \
    # ansible-core/alpine314/

# https://github.com/willhallonline/docker-ansible/blob/v4.3.2/ansible-core/alpine314/Dockerfile
# pull base image
FROM alpine:3.14

# ARG ANSIBLE_CORE_VERSION
# ARG ANSIBLE_LINT
# ARG ANSIBLE_VERSION
# ENV ANSIBLE_CORE_VERSION ${ANSIBLE_CORE_VERSION}
# ENV ANSIBLE_LINT ${ANSIBLE_LINT}
# ENV ANSIBLE_VERSION ${ANSIBLE_VERSION}
ENV ANSIBLE_CORE_VERSION "2.13.7"
ENV ANSIBLE_LINT "5.4.0"
ENV ANSIBLE_VERSION "6.7.0"

# # Labels.
# LABEL maintainer="will@willhallonline.co.uk" \
#     org.label-schema.schema-version="1.0" \
#     org.label-schema.build-date=$BUILD_DATE \
#     org.label-schema.vcs-ref=$VCS_REF \
#     org.label-schema.name="willhallonline/ansible" \
#     org.label-schema.description="Ansible inside Docker" \
#     org.label-schema.url="https://github.com/willhallonline/docker-ansible" \
#     org.label-schema.vcs-url="https://github.com/willhallonline/docker-ansible" \
#     org.label-schema.vendor="Will Hall Online" \
#     org.label-schema.docker.cmd="docker run --rm -it -v $(pwd):/ansible ~/.ssh/id_rsa:/root/id_rsa willhallonline/ansible:2.12-alpine-3.14"

# RUN export domain="mirrors.aliyun.com"; \
RUN export domain="mirrors.ustc.edu.cn"; \
  echo "http://$domain/alpine/v3.14/main" > /etc/apk/repositories; \
  echo "http://$domain/alpine/v3.14/community" >> /etc/apk/repositories


RUN apk --no-cache add \
        sudo \
        python3\
        py3-pip \
        openssl \
        ca-certificates \
        sshpass \
        openssh-client \
        rsync \
        git && \
    apk --no-cache add --virtual build-dependencies \
        python3-dev \
        libffi-dev \
        musl-dev \
        gcc \
        cargo \
        openssl-dev \
        libressl-dev \
        build-base && \
    pip3 install --upgrade pip wheel && \
    pip3 install --upgrade cryptography cffi && \
    pip3 install ansible-core==${ANSIBLE_CORE_VERSION} && \
    # pip3 install ansible==${ANSIBLE_VERSION} && \
    pip3 install --ignore-installed  ansible-lint==${ANSIBLE_LINT} && \
    pip3 install mitogen jmespath && \
    pip3 install --upgrade pywinrm && \
    # # rdeck's ansible-hosts
    #  ERR:ansible-core 2.13.7 requires jinja2>=3.0.0, but you have jinja2 2.10.1 which is incompatible.
    #  Successfully installed jinja2-2.10.1
    # pip3 install jinja2==2.10.1 && \
    #  Downloading MarkupSafe-1.1.1.tar.gz (19 kB)
    #  Preparing metadata (setup.py) ... error
    # pip3 install markupsafe==1.1.1 && \
    # 
    apk del build-dependencies && \
    rm -rf /var/cache/apk/* && \
    rm -rf /root/.cache/pip && \
    rm -rf /root/.cargo

RUN mkdir /ansible && \
    mkdir -p /etc/ansible && \
    echo 'localhost' > /etc/ansible/hosts

WORKDIR /ansible

CMD [ "ansible-playbook", "--version" ]