FROM registry.cn-shenzhen.aliyuncs.com/infrastlabs/alpine-ext:weak

ARG TARGETPLATFORM
WORKDIR /down
# test -z "$(echo $TARGETPLATFORM |grep arm)"
RUN echo "mkdir -p \$TARGETPLATFORM; cd \$TARGETPLATFORM" > /bin/tplat; \
  chmod +x /bin/tplat

# containerd
RUN tplat; curl -O -fSL https://ghproxy.com/https://github.com/containerd/containerd/releases/download/v1.6.15/containerd-1.6.15-linux-amd64.tar.gz
# snapshotter
RUN tplat; curl -O -fSL https://ghproxy.com/https://github.com/containerd/fuse-overlayfs-snapshotter/releases/download/v1.0.5/containerd-fuse-overlayfs-1.0.5-linux-amd64.tar.gz
# cni 39M
RUN tplat; curl -O -fSL https://ghproxy.com/https://github.com/containernetworking/plugins/releases/download/v1.2.0/cni-plugins-linux-amd64-v1.2.0.tgz
# runc
RUN tplat; curl -o runc -fSL https://ghproxy.com/https://github.com/opencontainers/runc/releases/download/v1.1.4/runc.amd64

# nerdctl
RUN tplat; curl -O -fSL https://ghproxy.com/https://github.com/containerd/nerdctl/releases/download/v1.1.0/nerdctl-1.1.0-linux-amd64.tar.gz
# crictl 22M
RUN tplat; curl -O -fSL https://ghproxy.com/https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.26.0/crictl-v1.26.0-linux-amd64.tar.gz

# k3s
RUN tplat; curl -O -fSL https://ghproxy.com/https://github.com/k3s-io/k3s/releases/download/v1.22.17%2Bk3s1/k3s
RUN tplat; curl -O -fSL https://ghproxy.com/https://github.com/k3s-io/k3s/releases/download/v1.22.17%2Bk3s1/k3s-arm64

# kubeedge
RUN tplat; curl -O -fSL https://ghproxy.com/https://github.com/kubeedge/kubeedge/releases/download/v1.10.3/kubeedge-v1.10.3-linux-amd64.tar.gz
RUN tplat; curl -O -fSL https://ghproxy.com/https://github.com/kubeedge/kubeedge/releases/download/v1.13.0/kubeedge-v1.13.0-linux-amd64.tar.gz
RUN ls -lh; find; tree -h;
