# https://github.com/willhallonline/docker-ansible/blob/d155dc9a98924c77ed3f5f7c4de384bd9f630e98/ansible28/alpine39/Dockerfile
# pull base image
FROM alpine:3.9

# Labels.
# LABEL maintainer="will@willhallonline.co.uk" \
#     org.label-schema.schema-version="1.0" \
#     org.label-schema.build-date=$BUILD_DATE \
#     org.label-schema.vcs-ref=$VCS_REF \
#     org.label-schema.name="willhallonline/ansible" \
#     org.label-schema.description="Ansible inside Docker" \
#     org.label-schema.url="https://github.com/willhallonline/docker-ansible" \
#     org.label-schema.vcs-url="https://github.com/willhallonline/docker-ansible" \
#     org.label-schema.vendor="Will Hall Online" \
#     org.label-schema.docker.cmd="docker run --rm -it -v $(pwd):/ansible -v ~/.ssh/id_rsa:/root/id_rsa willhallonline/ansible:2.7-alpine-3.9"


# RUN export domain="mirrors.aliyun.com"; \
RUN export domain="mirrors.ustc.edu.cn"; \
  echo "http://$domain/alpine/v3.9/main" > /etc/apk/repositories; \
  echo "http://$domain/alpine/v3.9/community" >> /etc/apk/repositories


RUN apk --no-cache add \
        sudo \
        python \
        py-pip \
        openssl \
        ca-certificates \
        sshpass \
        openssh-client \
        rsync \
        git && \
    apk --no-cache add --virtual build-dependencies \
        python-dev \
        libffi-dev \
        openssl-dev \
        build-base && \
    pip install --upgrade pip cffi && \
    pip install ansible==2.8.7 && \
    pip install mitogen ansible-lint && \
    pip install --upgrade pywinrm && \
    apk del build-dependencies && \
    rm -rf /var/cache/apk/*

RUN mkdir /ansible && \
    mkdir -p /etc/ansible && \
    echo 'localhost' > /etc/ansible/hosts

WORKDIR /ansible

CMD [ "ansible-playbook", "--version" ]


# ERR:
# > [linux/amd64 3/5] RUN apk --no-cache add         sudo         python         py-pip         openssl         ca-certificates         sshpass         openssh-client         rsync         git &&     apk --no-cache add --virtual build-dependencies         python-dev         libffi-dev         openssl-dev         build-base &&     pip install --upgrade pip cffi &&     pip install ansible==2.8.7 &&     pip install mitogen ansible-lint &&     pip install --upgrade pywinrm &&     apk del build-dependencies &&     rm -rf /var/cache/apk/*:
# 46.54       self._add_defaults_ext()
# 46.54     File "/tmp/pip-build-env-h49nEO/overlay/lib/python2.7/site-packages/setuptools/command/py36compat.py", line 120, in _add_defaults_ext
# 46.54       self.filelist.extend(build_ext.get_source_files())
# 46.54     File "setup.py", line 201, in get_source_files
# 46.54       self.cython_sources(ext.sources, ext)
# 46.54     File "/usr/lib/python2.7/distutils/cmd.py", line 105, in __getattr__
# 46.54       raise AttributeError, attr
# 46.54   AttributeError: cython_sources
# 46.54   ----------------------------------------
# 46.54 ERROR: Command errored out with exit status 1: /usr/bin/python2 /usr/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpwaRwY3 Check the logs for full command output.

